// <auto-generated />
using System;
using ImageCore.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImageCore.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ImageDbContext))]
    [Migration("20190301113830_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImageCore.Persistence.EntityFramework.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessType");

                    b.Property<byte[]>("Bytes");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("Format");

                    b.Property<int>("Height");

                    b.Property<bool>("IsTemp");

                    b.Property<string>("Key")
                        .HasMaxLength(256);

                    b.Property<long>("Length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("[Key] IS NOT NULL");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
